liba32android_add_test_executable(cpu_smoke tests/cpu/cpu_smoke.cpp)
liba32android_add_test_executable(cpu_execution tests/cpu/cpu_execution.cpp)
liba32android_add_test_executable(cpu_fastmem_test tests/cpu/cpu_fastmem.cpp)

add_test(NAME guest_arm_return_42 COMMAND cpu_smoke arm)
add_test(NAME guest_thumb_return_42 COMMAND cpu_smoke thumb)
add_test(NAME guest_register_state COMMAND cpu_execution registers)
add_test(NAME guest_branch COMMAND cpu_execution branch)
add_test(NAME guest_call COMMAND cpu_execution call)
add_test(NAME guest_memory_load_store COMMAND cpu_execution memory)
add_test(NAME guest_stack COMMAND cpu_execution stack)
add_test(NAME guest_thumb_branch COMMAND cpu_execution thumb_branch)
add_test(NAME guest_thumb_call COMMAND cpu_execution thumb_call)
add_test(NAME guest_thumb_memory_load_store COMMAND cpu_execution thumb_memory)
add_test(NAME guest_thumb_stack COMMAND cpu_execution thumb_stack)
add_test(NAME guest_thumb_svc_exception COMMAND cpu_execution thumb_svc)
add_test(NAME guest_svc_resume_state COMMAND cpu_execution svc_resume)
add_test(NAME guest_instruction_fetch_fault COMMAND cpu_execution fetch_fault)
add_test(NAME guest_thumb_data_fault COMMAND cpu_execution thumb_data_fault)
add_test(NAME guest_persistent_jit_session COMMAND cpu_execution session)
add_test(NAME dynarmic_fastmem_and_fallback COMMAND cpu_fastmem_test)
